Message: src/tests/test_message.cpp src/Tools/CFNP/Message/Subprotocols/FourthHandshake.cpp src/Tools/CFNP/Message/Message.cpp src/Tools/Encoding.cpp
	g++ -o bin/tests/test_message src/tests/test_message.cpp src/Tools/CFNP/Message/Subprotocols/FourthHandshake.cpp src/Tools/CFNP/Message/Message.cpp src/Tools/Encoding.cpp

Encoding: src/tests/test_encoding.cpp src/Tools/Encoding.cpp
	g++ -o bin/tests/test_encoding src/tests/test_encoding.cpp src/Tools/Encoding.cpp