Message: src/Tools/Message.cpp
	g++ -o bin/Message src/Tools/Message.cpp

Encoding: src/tests/test_encoding.cpp src/Tools/Encoding.cpp
	g++ -o bin/tests/test_encoding src/tests/test_encoding.cpp src/Tools/Encoding.cpp